GET http://127.0.0.1:8081/order
Content-Type: application/json

###
GET http://127.0.0.1:8081/order/2020-04-06-01
Content-Type: application/json

###
GET http://127.0.0.1:8081/order/2020-04-06-01/total
Content-Type: application/json